import assert from "node:assert/strict";
import { PresenceAudio } from "../audio.js";
import { PRESENCE_CONFIG } from "../presence.js";
import { FakeAudioContext } from "./fake-audio.mjs";

const audio = new PresenceAudio(FakeAudioContext);
const event = { type:"RUSTLE", yaw:90 };
assert.equal(audio.context,null,"no AudioContext at page load");
assert.equal(audio.play(event,0,85),false);
await audio.unlock();
const context = audio.context;
assert.equal(audio.state,"running");
assert.equal(audio.master.gain.value,0.55*0.12);
for(const type of Object.keys(PRESENCE_CONFIG.sounds)) {
  assert.equal(audio.play({type,yaw:90},0,10),true);
  const voice = audio.voice;
  assert.ok(voice.source.stopTimes[0] <= 0.72, "finite source lifetime");
  assert.equal(audio.lastSpatial.pan,0.7);
  assert.ok(audio.lastSpatial.effectiveVolume<=0.12);
  audio.spatial({type,yaw:90},180,10);
  assert.equal(audio.lastSpatial.pan,-0.7,"turning updates pan");
  audio.stop();
  assert.equal(audio.voice,null);
  assert.ok(voice.nodes.every(node=>node.disconnected));
}
audio.play(event,0,10);
const previous=audio.voice;
audio.play(event,0,10);
assert.ok(previous.nodes.every(node=>node.disconnected),"one voice only");
audio.voice.source.onended();
assert.equal(audio.voice,null,"natural completion cleanup");
audio.setEnabled(false);
const starts=context.starts;
assert.equal(audio.play(event,0,10),false);
assert.equal(context.starts,starts,"SOUND OFF no request");
assert.equal(await audio.unlock(),false);
audio.setEnabled(true);
context.state="suspended";
await audio.unlock();
assert.equal(audio.context,context,"resume reuses context");
assert.equal(audio.state,"running");
context.createStereoPanner=undefined;
assert.equal(audio.play(event,0,10),true,"mono fallback");
audio.stop();
context.createOscillator=()=>{throw new Error('unsupported')};
assert.equal(audio.play({type:"TAP",yaw:0},0,10),false);
assert.equal(audio.voice,null);
assert.ok(audio.error);
const unsupported=new PresenceAudio(undefined);
assert.equal(unsupported.state,"unsupported");
assert.equal(await unsupported.unlock(),false);
console.log("Audio: gesture initialization, four finite sounds, bounded gain, live pan, cleanup, mute, resume and fallback passed");
